export const units = new Map([
  ["Archer", { name: "Archer",
    castle: "Castle",
    nature: "Good",
    level: 2,
    aiValue: 126,
    type: "ranged",
    unitPortrait: "",
    castleImage: ""}],
  ["Pikeman",{ name: "Pikeman",
    castle: "Castle",
    nature: "Good",
    level: 1,
    aiValue: 80,
    type: "melee",
    unitPortrait: "",
    castleImage: ""}]]);
