export const units = [
  {
    ID: "Cas1",
    Name: "Pikeman",
    Town: "Castle",
    Tier: 1,
    AttackType: "Melee",
    Speed: 4,
    Attack: 4,
    Def: 5,
    DmgMin: 1,
    DmgMax: 3,
    Health: 10,
    Cost: 60,
    Growth: 14,
    Aligment: "Good",
    Special: "Immune to jousting"
  },
  {
    ID: "Cas1U",
    Name: "Halberdier",
    Town: "Castle",
    Tier: 1,
    AttackType: "Melee",
    Speed: 5,
    Attack: 6,
    Def: 5,
    DmgMin: 2,
    DmgMax: 3,
    Health: 10,
    Cost: 75,
    Growth: 14,
    Aligment: "Good",
    Special: "Immune to jousting"
  },
  {
    ID: "Cas2",
    Name: "Archer",
    Town: "Castle",
    Tier: 2,
    AttackType: "Ranged",
    Speed: 4,
    Attack: 6,
    Def: 3,
    DmgMin: 2,
    DmgMax: 3,
    Health: 10,
    Cost: 100,
    Growth: 9,
    Aligment: "Good"
  },
  {
    ID: "Cas2U",
    Name: "Marksman",
    Town: "Castle",
    Tier: 2,
    AttackType: "Ranged, Double Attack",
    Speed: 6,
    Attack: 6,
    Def: 3,
    DmgMin: 2,
    DmgMax: 3,
    Health: 10,
    Cost: 150,
    Growth: 9,
    Aligment: "Good",
    Special: "Ranged (24 shots), Double attack"
  },
  {
    ID: "Cas3",
    Name: "Griffin",
    Town: "Castle",
    Tier: 3,
    AttackType: "Melee",
    Speed: 6,
    Attack: 8,
    Def: 8,
    DmgMin: 3,
    DmgMax: 6,
    Health: 25,
    Cost: 200,
    Growth: 7,
    Aligment: "Good",
    Special: "Flying, Two retaliations"
  },
  {
    ID: "Cas3U",
    Name: "Royal Griffin",
    Town: "Castle",
    Tier: 3,
    AttackType: "Melee",
    Speed: 9,
    Attack: 9,
    Def: 9,
    DmgMin: 3,
    DmgMax: 6,
    Health: 25,
    Cost: 240,
    Growth: 7,
    Aligment: "Good",
    Special: "Flying, Unlimited retaliations"
  },
  {
    ID: "Cas4",
    Name: "Swordsman",
    Town: "Castle",
    Tier: 4,
    AttackType: "Melee",
    Speed: 5,
    Attack: 10,
    Def: 12,
    DmgMin: 6,
    DmgMax: 9,
    Health: 35,
    Cost: 300,
    Growth: 4,
    Aligment: "Good",
    Special: "No speciallity"
  },
  {
    ID: "Cas4U",
    Name: "Crusader",
    Town: "Castle",
    Tier: 4,
    AttackType: "Melee, Double Attack",
    Speed: 6,
    Attack: 12,
    Def: 12,
    DmgMin: 7,
    DmgMax: 10,
    Health: 35,
    Cost: 400,
    Growth: 4,
    Aligment: "Good",
    Special: "Double attack"
  },
  {
    ID: "Cas5",
    Name: "Monk",
    Town: "Castle",
    Tier: 5,
    AttackType: "Ranged",
    Speed: 5,
    Attack: 12,
    Def: 7,
    DmgMin: 10,
    DmgMax: 12,
    Health: 30,
    Cost: 400,
    Growth: 3,
    Aligment: "Good",
    Special: "Ranged (12 shots)"
  },
  {
    ID: "Cas5U",
    Name: "Zealot",
    Town: "Castle",
    Tier: 5,
    AttackType: "Ranged",
    Speed: 7,
    Attack: 12,
    Def: 10,
    DmgMin: 10,
    DmgMax: 12,
    Health: 30,
    Cost: 450,
    Growth: 3,
    Aligment: "Good",
    Special: "Ranged (24 shots), No melee penalty"
  },
  {
    ID: "Cas6",
    Name: "Cavalier",
    Town: "Castle",
    Tier: 6,
    AttackType: "Melee",
    Speed: 7,
    Attack: 15,
    Def: 15,
    DmgMin: 15,
    DmgMax: 25,
    Health: 100,
    Cost: 1000,
    Growth: 2,
    Aligment: "Good",
    Special: "Jousting"
  },
  {
    ID: "Cas6U",
    Name: "Champion",
    Town: "Castle",
    Tier: 6,
    AttackType: "Melee",
    Speed: 9,
    Attack: 16,
    Def: 16,
    DmgMin: 20,
    DmgMax: 25,
    Health: 100,
    Cost: 1200,
    Growth: 2,
    Aligment: "Good",
    Special: "Jousting"
  },
  {
    ID: "Cas7",
    Name: "Angel",
    Town: "Castle",
    Tier: 7,
    AttackType: "Melee",
    Speed: 12,
    Attack: 20,
    Def: 20,
    DmgMin: 50,
    DmgMax: 50,
    Health: 200,
    Cost: "3000, 1 gem",
    Growth: 1,
    Aligment: "Good",
    Special: "Flying, Hates Devils, Morale +1"
  },
  {
    ID: "Cas7U",
    Name: "Archangel",
    Town: "Castle",
    Tier: 7,
    AttackType: "Melee, Spell Caster",
    Speed: 18,
    Attack: 30,
    Def: 30,
    DmgMin: 50,
    DmgMax: 50,
    Health: 250,
    Cost: "5000, 3 gem",
    Growth: 1,
    Aligment: "Good",
    Special: "Flying, Hates Devils, Resurrection, Morale +1"
  }
];
