export const units = [
  { name: "Archer",
    castle: "Castle",
    nature: "Good",
    level: 2,
    aiValue: 126,
    type: "ranged",
    unitPortrait: "",
    castleImage: ""},
  { name: "Pikeman",
    castle: "Castle",
    nature: "Good",
    level: 1,
    aiValue: 126,
    type: "melee",
    unitPortrait: "",
    castleImage: ""},
];
